---
 - hosts: Webserver

   tasks:

    - name: apt-get clean
      shell: apt-get clean
      become: true
      become_user: root

    - name: apt-get update
      shell: apt-get update
      become: true
      become_user: root

    - name: ensure Docker is installed
      apt: name=docker.io update_cache=yes
      become: yes

    - name: ensure Docker Compose is installed
      apt: name=docker-compose update_cache=yes
      become: yes

    - name: Add jenkins to docker group
      shell: usermod -aG docker jenkins
      become: true
      become_user: root

    - name: ensure Docker is running
      service: name=docker state=started
      become: true
      become_user: jenkins
