---
 - hosts: Webserver

   tasks:

    - name: apt-get clean
      shell: apt-get clean
      become: true
      become_user: root

    - name: apt-get update
      shell: apt-get update
      become: true
      become_user: root

    - name: ensure Apache is installed
      apt: name=docker.io update_cache=yes
      become: yes

    - name: ensure Apache is installed
      apt: name=docker-compose update_cache=yes
      become: yes

    - name: ensure docker is running
      service: name=docker state=started

    - name: Remove existing containers
      shell: docker-compose rm -f -s
      become: true
      become_user: root
      
    - name: Start Wordpress Containers
      shell: docker-compose run -d
      become: true
      become_user: root
